// Seed list of startups / scale-ups by HQ country.
// Format: "Company Name" or "Company Name|slug1,slug2" when the ATS slug differs from the name.
// Indian-HQ companies are intentionally excluded.
// Add companies freely — the weekly discovery run works out which ATS each one uses.

export const SEEDS = {
  UK: [
    "Monzo", "Revolut", "Wise|wise,transferwise", "Starling Bank|starlingbank", "GoCardless", "Checkout.com|checkoutcom,checkout",
    "Deliveroo", "Cleo|cleoai,cleo", "Tide", "Zopa", "OakNorth", "Thought Machine|thoughtmachine", "Paddle", "Primer|primer,primerapi",
    "TrueLayer", "Yapily", "Moneybox", "Chip|getchip", "Plum|withplum", "Curve|curve,imaginecurve", "Marshmallow", "Cuvva", "Zego",
    "Bloom & Wild|bloomandwild", "Gousto", "Onfido", "Synthesia", "ElevenLabs|elevenlabs", "Stability AI|stabilityai", "PolyAI|polyai",
    "Faculty|faculty,facultyai", "Wayve", "Tractable", "Cera|cera,ceracare", "Multiverse", "Beamery", "Snyk", "CMR Surgical|cmrsurgical",
    "Motorway", "Farewill", "Lendable", "Ravelin", "ComplyAdvantage", "Signal AI|signalai", "Quantexa", "Peak AI|peak,peakai",
    "Genie AI|genieai", "Luminance", "Robin AI|robinai", "Juro", "Beauhurst", "Hofy", "Omnipresent", "Oyster HR|oyster,oysterhr",
    "Payhawk", "Soldo", "Ebury", "Banked", "Modulr|modulrfinance,modulr", "ClearBank", "Griffin|griffin,griffinbank", "Kroo",
    "Allica Bank|allicabank", "Freetrade", "Nutmeg", "Carmoola", "Huma|huma,humatherapeutics", "Kheiron Medical|kheiron",
    "Healx", "Isomorphic Labs|isomorphiclabs", "CuspAI|cuspai", "Nscale", "PhysicsX", "V7|v7labs,v7", "Unitary", "Cognism",
    "Lyst", "Depop", "Thriva", "Numan", "What3words", "Improbable", "Ometria", "Attest|attest,askattest", "Carwow", "Zapp",
    "PrimaryBid", "Seedrs", "Crowdcube", "Tembo|tembomoney,tembo", "10x Banking|10xbanking,10x", "Snoop", "Hopin", "Paddle",
    "Nothing|nothing,nothingtech", "Fundment", "Bink", "Ophelos", "Ember|ember,emberfund", "Pillar", "Wagestream", "Uncapped",
    "Previse", "Tully", "Duco", "Kaluza", "Octopus Energy|octopusenergy", "Ohme", "Pod Point|podpoint", "Bulb", "Zilch",
    "Laybuy", "Payl8r", "Airalo", "Hurr", "Vinterior", "Trouva", "Papier", "Cazoo", "Hungry Panda|hungrypanda",
    "Rebel Energy", "Paddle", "Hyperexponential|hyperexponential", "Cytora", "Artificial|artificiallabs,artificial",
    "Superscript", "Flock", "Laka", "Zego", "Lemonade", "Pollen", "Bolt|bolt", "Trustonic", "Privitar", "Lightfoot",
    "Clearscore", "Ravio", "Stitch", "Gearset", "Hiive", "Wefarm", "Paddle", "Heron Data|herondata", "Lantum", "Birdie|birdie,birdiecare",
    "Accurx", "Patchwork Health|patchworkhealth", "Feedr", "Paddle", "Dojo|dojo,paymentsense", "Butternut Box|butternutbox",
    "Mintago", "Moneyhub", "Fintern", "Lloyds", "Cambridge Quantum", "Quantinuum", "Oxford Ionics|oxfordionics", "Riverlane",
    "Phasecraft", "Ori|ori,oriindustries", "Humanloop", "Tessl", "Synthace", "Luminous", "Adarga", "Helsing", "Paddle",
    "Hadean", "Conjecture", "Faculty", "Unlikely AI|unlikelyai", "Maze|maze,mazehq", "Encord", "Prolific", "Deep Render|deeprender",
    "Instil", "Paddle", "Paysend", "Ziglu", "Kraken Technologies|krakentechnologies", "LabGenius", "Mindtrace", "Cogna",
    "Wordsmith", "Granola", "Lindus Health|lindushealth", "Flo Health|flohealth", "Paddle", "Hemi", "Fyxer", "Nory", "Supercritical",
    "Satellite Vu|satellitevu", "Open Cosmos|opencosmos", "Space Forge|spaceforge", "Astroscale", "Paddle", "Nothing",
    "Wintermute", "Nethermind", "Aave|aave,avara", "Copper|copper,coppertechnologies", "Zumo", "Elliptic", "Chainalysis",
    "CoinShares", "Gemini", "Paddle", "Fnality", "Clear Junction|clearjunction", "Fluidly", "Swoop", "Codat", "Railsr",
    "Thanks Ben|thanksben", "Juniper Education", "Paddle", "Vitt", "Paddle", "Hyperscience", "Tractable", "Speechmatics",
    "Paddle", "Lockwood Publishing", "Hutch", "Space Ape|spaceape", "Paddle", "Bumble", "Hinge",
  ],
  Germany: [
    "N26", "Trade Republic|traderepublic", "Scalable Capital|scalablecapital,scalable", "Raisin", "Solaris|solaris,solarisbank",
    "Mambu", "Personio", "Celonis", "Contentful", "GetYourGuide|getyourguide", "Flix|flix,flixbus", "Enpal", "1Komma5|1komma5grad,1komma5",
    "Sennder", "Forto", "Taxfix", "Clark", "Wefox", "Grover", "Tier|tier,tiermobility", "Choco", "Pitch", "Helsing",
    "Aleph Alpha|alephalpha", "DeepL", "Black Forest Labs|blackforestlabs", "Parloa", "n8n", "Langfuse", "Staffbase",
    "Leapsome", "Moss|getmoss,moss", "Pliant", "Billie", "Mondu", "Upvest", "Finn|finn,finnauto", "Omio", "Blinkist",
    "Babbel", "Tourlane", "Zenjob", "Workmotion", "Deskbird", "Kenjo", "Circula", "Candis", "Buena", "Ecosia", "Sunfire",
    "Isar Aerospace|isaraerospace", "Quantum Systems|quantumsystems", "Neura Robotics|neurarobotics", "Agile Robots|agilerobots",
    "Konux", "Scoutbee", "Productsup", "SumUp", "Adjust", "Commercetools", "Spryker", "Emporix", "Penta", "Kontist",
    "Ivy|getivy,ivy", "Unzer", "Ada Health|adahealth", "Kaia Health|kaiahealth", "Avi Medical|avimedical", "Temedica", "Enmacc",
    "Remberg", "Cognigy", "Merantix", "Twaice", "Sastrify", "Proxima Fusion|proximafusion", "Marvel Fusion|marvelfusion",
    "The Exploration Company|theexplorationcompany", "Planet A Foods|planetafoods", "Hive|hive,hivetechnology", "Airup|airup",
    "Knowunity", "Simpleclub", "GoStudent", "Heyday", "Holidu", "Smava", "Finanzguru", "Bonify", "Friday Finance|fridayfinance",
    "Qonto", "Agicap", "Tomorrow Bank|tomorrow", "Vivid Money|vivid,vividmoney", "Nuri", "Coinbase", "Bitwala", "Nuri",
    "Parity|parity,paritytech", "Web3 Foundation|web3foundation", "Gnosis", "Safe|safe,safeglobal", "Matter Labs|matterlabs",
    "Tools for Humanity|toolsforhumanity", "Iota Foundation|iotafoundation", "Celo", "Boerse Stuttgart Digital|bsdigital",
    "Solaris", "Mercury", "Contentsquare", "Payone", "Fincompare", "Lendis", "Getsafe", "Ottonova", "Element Insurance|element",
    "Heidi Pay|heidipay", "Ratepay", "Paypal", "Klarna", "Hey Car|heycar", "Instafreight", "Cargoone|cargoone", "Zeitgold",
    "Everstox", "Vay", "Volocopter", "Lilium", "Tado", "Thermondo", "Zolar", "Node.energy|nodeenergy", "Enersis", "Envelio",
    "Instagrid", "Cylib", "Traceless", "Plan A|plana,planaearth", "Planetly", "Carbonfuture", "Klim", "Ineratec",
    "Buynomics", "Uberall", "Contentful", "Usercentrics", "Userlane", "Mentimeter", "Luminovo", "Workpath", "Hacker School",
    "Rasa", "Deepset", "Jina AI|jinaai", "Langdock", "Tacto", "Beams", "Hemovent", "Formo", "Yfood", "Flink",
    "Gorillas", "Wolt", "Hellofresh", "Delivery Hero|deliveryhero", "Zalando", "Auto1", "Wonderkind", "Stepstone",
    "Freeletics", "Urban Sports Club|urbansportsclub", "Egym", "Kuehne", "Frontify", "Pitch", "Airfocus", "Cobra",
  ],
  France: [
    "Qonto", "Alan", "Doctolib", "PayFit|payfit", "Pennylane", "Swile", "Spendesk", "Agicap", "Mirakl", "Contentsquare",
    "Back Market|backmarket", "Ledger", "Sorare", "Ankorstore", "Mistral AI|mistral,mistralai", "Hugging Face|huggingface",
    "Dataiku", "Algolia", "Aircall", "Front|frontapp,front", "Ornikar", "Malt", "Libeo", "Lydia|lydia,sumeria", "Shift Technology|shifttechnology",
    "ManoMano", "Vestiaire Collective|vestiairecollective", "BlaBlaCar|blablacar", "Deezer", "Brevo|brevo,sendinblue", "Livestorm",
    "Lemlist", "PhantomBuster", "Dust|dust,dusttt", "Photoroom", "H Company|hcompany", "Poolside|poolside,poolsideai", "Pigment",
    "Yousign", "Swan|swan,swanio", "Lemonway", "Didomi", "Welcome to the Jungle|wttj,welcometothejungle", "Botify", "Sunday|sundayapp,sunday",
    "Zenchef", "Skello", "Side", "Indy", "Shine", "Memo Bank|memobank", "Fabriq", "Hivebrite", "Akeneo", "Matera",
    "Descartes Underwriting|descartesunderwriting", "Deepki", "Electra", "Verkor", "Owkin", "Nabla", "EcoVadis|ecovadis",
    "Sweep", "Greenly", "Payplug", "Upflow", "Kiln", "Zama", "Kaiko", "Flowdesk", "Coinhouse", "Paymium", "Stackeo",
    "Mooncard", "Pretto", "Luko", "Leocare", "Stello", "Hiboo", "Cooltra", "Getaround", "Zenly", "Heetch", "Lalilo",
    "Openclassrooms", "Livementor", "Jobteaser", "Contentsquare", "Batch", "Mailjet", "Sendinblue", "Crisp", "Axeptio",
    "Scaleway", "OVHcloud|ovhcloud", "Clever Cloud|clevercloud", "Platform.sh|platformsh", "Sqreen", "Alma|alma,getalma",
    "Younited", "Oney", "Treezor", "Lemon Way", "Hipay", "Stuart", "Cityscoot", "Dott|dott,ridedott", "Zity", "Ector",
    "Voodoo", "Homa|homagames,homa", "Ubisoft", "Believe", "Dailymotion", "Qobuz", "Alan", "Moka.care|mokacare",
    "Doctrine", "Legalstart", "Captain Contrat|captaincontrat", "Payfit", "Lucca", "Factorial", "Choose", "Cajoo",
  ],
  Sweden: [
    "Klarna", "Epidemic Sound|epidemicsound", "Voi|voi,voitechnology", "Tink", "Trustly", "Kry|kry,livi", "Einride",
    "Lovable|lovable", "Legora|legora", "Sana Labs|sanalabs,sana", "Depict|depict,depictai", "Mentimeter", "Anyfin", "Juni",
    "Truecaller", "Budbee", "Instabox", "Karma", "Stegra|stegra,h2greensteel", "Normative", "Doconomy", "Worldfavor",
    "Fishbrain", "Detectify", "Storytel", "Bokio", "Froda", "Qred", "Brite|brite,britepayments", "Zimpler", "Hedvig",
    "Alva Labs|alvalabs", "Teamtailor", "Quinyx", "Kognity", "Mindler", "Natural Cycles|naturalcycles", "Neko Health|nekohealth",
    "Flower|flower,flowerse", "Ingrid", "Airmee", "Hygglo", "Cling", "Tracklib", "Sellpy", "Kivra", "Readly", "Tibber",
    "Sinch", "iZettle", "Trustly", "Lendo", "Rocker", "Northmill", "Lunar", "Pleo", "Revolut", "Minna Technologies|minnatechnologies",
    "Imagine AI", "Volta Greentech|voltagreentech", "Polestar", "Vultus", "Carbon Cloud|carboncloud", "Milkywire", "Aira|aira,airahome",
    "Hemnet", "Booli", "Qasa", "Hemma", "Mathem", "Oda", "Tise", "Vinted", "Sellpy", "Mnd", "Paradox",
    "Hidden Dreams", "Embark", "Avalanche Studios", "Sharpfin", "Kidbrooke", "Lysa", "Opti", "Tre Kronor", "Instabee",
    "Watchit", "Apotea", "Doktor.se|doktorse", "Werlabs", "Cellink", "Zwapgrid", "Wint", "Majority", "Estateguru",
    "Glimstedt", "Superlative", "Nobina", "Einride", "Hugo", "Leeroy", "Planday", "Vainu", "Ctrl", "Tessin",
  ],
  Norway: [
    "Kahoot", "Oda", "Vipps", "Cognite", "reMarkable|remarkable", "Airthings", "Nomono", "Unacast", "Otovo", "Sanity",
    "Whereby", "Xeneta", "Strise", "Motimate", "Easee", "Zaptec", "Heimdal Power|heimdalpower", "Boost.ai|boostai",
    "Tibber", "Spacemaker", "Tise", "Vend", "Finn", "Kolonial", "Cognite", "Dune Analytics|duneanalytics,dune", "Nordic Semiconductor",
    "Aker Horizons", "Autostore", "Ocean Sun|oceansun", "Hy24", "Morrow Batteries|morrowbatteries", "Freyr", "Nel", "Corvus Energy|corvusenergy",
    "Kongsberg", "Zelo", "Neonomics", "Tink", "Bluefish", "Pexip", "Huddly", "Ignite", "Crayon", "Visma", "Payr",
    "Lendo", "Bulder", "Svea", "Luminar", "Kron", "Nordnet", "Kyte", "Chooose|chooose", "Loop", "Bid", "No Isolation|noisolation",
    "Dignio", "Kry", "Ably", "Gelato", "Scoutbase", "Unacast", "Trainerly", "Fjord", "Ada", "Neodroid",
  ],
  Denmark: [
    "Pleo", "Lunar", "Trustpilot", "Vivino", "Too Good To Go|toogoodtogo", "Templafy", "Planday", "Veo|veo,veotechnologies",
    "Queue-it|queueit", "Siteimprove", "GoMore", "Corti", "Dixa", "Tradeshift", "Airtame", "Monta", "Ageras", "Contractbook",
    "Legal Desk|legaldesk", "Unwire", "Peakon", "Pento", "Holion", "Hempel", "Firmafon", "Worksome", "Hiper", "Airtame",
    "Normative", "Continia", "Ordrestyring", "Queue-it", "Zendesk", "Unity", "Napatech", "Better Collective|bettercollective",
    "Tame", "Tonsser", "Joe & the Juice|joeandthejuice", "Vestas", "Ørsted", "Copenhagen Atomics|copenhagenatomics", "Seaborg",
    "Everfund", "Flatpay", "Onlinepos", "Shape", "Leadfamly", "Airfryer", "Penneo", "Uniwise", "Labster", "Kahoot", "Cobuilder",
    "Plecto", "Heartcore", "Sleeknote", "Relesys", "Voluntarily", "Hygge", "ChargePoint", "Evida", "Radiobotics", "Cortrium",
  ],
  Finland: [
    "Wolt", "Supercell", "Oura", "Aiven", "Smartly|smartly,smartlyio", "ICEYE|iceye", "Relex|relex,relexsolutions", "Swappie",
    "Varjo", "Yousician", "MaaS Global|maasglobal,whim", "Pipedrive", "Qvantel", "Distance Technologies|distancetechnologies",
    "Sievo", "Enfuce", "Holvi", "Framery", "Virta", "IQM|iqm,meetiqm", "Wirepas", "Vainu", "Leadfeeder", "Dealfront",
    "Hoxhunt", "Zervant", "Rightware", "Silo AI|siloai", "Rovio", "Small Giant Games|smallgiantgames", "Next Games|nextgames",
    "Remedy", "Metacore", "Housemarque", "Kielo", "ResQ Club|resqclub", "Foodie", "Zadaa", "Solar Foods|solarfoods",
    "Infinited Fiber|infinitedfiber", "Carbo Culture|carboculture", "Nuclear Power", "Steady Energy|steadyenergy", "Kempower",
    "Aiforia", "Kaiku Health|kaikuhealth", "Nightingale Health|nightingalehealth", "Mehiläinen", "Tietoevry", "Paytrail", "Maventa",
    "Kasko", "Vertaa", "Scoro", "Workland", "Eficode", "Futurice", "Reaktor", "Taiste", "Unikie", "Nitor", "Loihde", "Basware",
  ],
  Estonia_Latvia_Lithuania: [
    "Bolt|bolt,boltapp", "Veriff", "Glia", "Lightyear", "Monese", "Starship|starship,starshiptechnologies", "Skeleton|skeleton,skeletontech",
    "Katana|katana,katanamrp", "Printful", "Sympower", "Montonio", "Salv", "Outfunnel", "Kilo Health|kilohealth,kilo",
    "Nord Security|nordsecurity", "Vinted", "Omnisend", "Hostinger", "Eneba", "Mintos", "Twino", "Toggl", "Pactum", "Fortumo",
    "Cleveron", "Zego", "Messente", "Testlio", "Scoro", "Pipedrive", "Wise", "Paxful", "Change", "Inbank", "Holm",
    "Paysera", "Kevin|kevin,getkevin", "Revolut", "Genie", "Ondato", "Iute", "Rubicon", "Estateguru", "Lokalise", "Sonarworks",
    "Giraffe360", "Turing College|turingcollege", "Tesonet", "Surfshark", "Oxylabs", "Attio", "Vendon", "PVcase|pvcase",
    "TransferGo|transfergo", "Nfq", "Deeper", "Bored Panda|boredpanda", "Kilo", "Cast AI|castai", "Heroes", "Pixelmatic",
    "Adapt", "Planet42", "Fortumo", "Wolt", "Bolt", "Nortal", "Ready Player Me|readyplayerme", "Alphablues", "ZeroTurnaround",
  ],
  Netherlands: [
    "Mollie", "Bunq", "Bitvavo", "Bird|bird,messagebird", "Picnic", "Sendcloud", "Framer", "Miro", "Backbase", "Tiqets",
    "WeTransfer", "Catawiki", "Otrium", "Studocu", "Fastned", "Lepaya", "Effectory", "Channable", "Swapfiets", "Felyx",
    "Dott", "Tebi", "Payaut", "Finom", "Ohpen", "Buckaroo", "Gynzy", "Recharge|recharge,rechargecom", "Weaviate", "Hiber",
    "Bux", "Tellow", "Mews", "Elastic", "Bolt", "Mambu", "Lightyear", "Crisp", "Kramp", "Bloqs", "Fairphone",
    "Lightyear Solar|lightyearone", "Vandebron", "Quooker", "Ace & Tate|aceandtate", "Rituals", "Hunkemöller", "Bol",
    "Coolblue", "Takeaway", "Booking", "Adyen", "Payvision", "Pay.nl|paynl", "Mobly", "Spotahome", "Ultimate",
    "Fuse", "Leadinfo", "Onesignal", "Nmbrs", "Visma", "Yoobi", "Deskbookers", "Sympany", "Emma", "Dexter", "Bloomon",
    "Frontier", "Surfsara", "Tailormade", "Flowtrack", "Tiller", "Adapcare", "Snappet", "Blendle", "Framer", "Hackajob",
    "Invest-NL", "Brand New Day|brandnewday", "Peaks", "Knab", "Bitonic", "BLOX", "Anycoin", "Coinmerce", "Finst",
    "Adapt", "Dockflow", "Seenons", "Relive", "Wakuli", "Fleks", "Temper", "YoungCapital", "Dataddo", "Studytube",
    "Healthy Workers", "Luscii", "Lifely", "Mendix", "Cloud Nine", "Enable", "Framer", "Tripaneer", "Bookinga", "Sanity",
  ],
  Ireland: [
    "Intercom", "Wayflyer", "Tines", "Flipdish", "Workvivo", "Fenergo", "LetsGetChecked|letsgetchecked", "Manna|manna,mannaaero",
    "Evervault", "Kitman Labs|kitmanlabs", "Phorest", "Trustap", "Nory", "Payslip", "Soapbox Labs|soapboxlabs", "Glofox",
    "Teamwork", "CluneTech|clunetech", "Xtremepush", "Buymie", "Stripe", "Hubspot", "Harmonic", "Tiktok", "Aylien",
    "Pointy", "Boxever", "Nuritas", "Voxpro", "Integrate", "Ding", "Fire|fire,firefinancial", "Swoop", "Leadership",
    "Openet", "Transfermate", "Viatel", "Waterford", "Poppulo", "Datalex", "Wrkit", "Hostelworld", "Dogpatch", "Zendesk",
    "Qualio", "Ocuco", "Arvoia", "Frankli", "Hubbub", "Getvisibility", "Cartrawler", "Carengage", "Travelport", "Keelvar",
    "Salesforce", "Gamma", "Squarespace", "Toast", "Personio", "Fonoa", "Sisu", "Plynk", "Flender", "Cognate",
  ],
  Switzerland: [
    "Scandit", "Frontify", "Beekeeper", "Climeworks", "Yokoy", "Sherpany", "Nexthink", "Wingtra", "ANYbotics|anybotics",
    "Numbrs", "Taurus", "Sygnum", "Bitcoin Suisse|bitcoinsuisse", "Lykke", "Smallpdf", "Veezoo", "Unique", "DFINITY|dfinity",
    "SonarSource|sonarsource", "Exoscale", "LatticeFlow|latticeflow", "Astrocast", "Neustark", "DeepJudge|deepjudge",
    "Proton|proton,protonag", "Near Foundation|nearfoundation,near", "Ethereum Foundation|ethereumfoundation", "Cardano Foundation|cardanofoundation",
    "Tezos Foundation", "Aeternity", "Swissquote", "Neon", "Yapeal", "Yuh", "Radicant", "Alpian", "Relio", "Selma Finance|selmafinance",
    "Descartes", "Advanon", "Contovista", "Loanboox", "Qumram", "GetYourGuide", "On", "Nothing", "Ava", "Sophia Genetics|sophiagenetics",
    "Bcomp", "Swiss Post", "Scewo", "Verity", "Flyability", "Fixposition", "Distalmotion", "Mindmaze", "Aktiia", "Biognosys",
    "Cutiss", "Nanolive", "Xelera", "Bexio", "Abacus", "Beqom", "Unit8", "Visium", "Dacuda", "Largo", "Scailyte", "Quantum Basel",
  ],
  Austria: [
    "Bitpanda", "GoStudent", "Refurbed", "Adverity", "Tractive", "Storyblok", "Hokify", "Anyline", "TourRadar|tourradar",
    "PlanRadar|planradar", "Bitmovin", "Byrd", "Prewave", "Fiskaly", "Finmatics", "Kiwi", "Parkbob", "Blockpit", "Coinpanion",
    "Twaice", "Cropster", "Robo Wunderkind|robowunderkind", "Hello Magenta", "Kape", "Emporia", "Runtastic", "Shpock",
    "Dynatrace", "Frequentis", "Tricentis", "Celum", "Proxyclick", "N26", "Riskine", "Nuki", "eversports|eversports", "Anybill",
    "Kapsch", "MyAbility", "Ondewo", "Craftworks", "Journi", "Magdalena", "Swarovski", "Froots", "Kinderpedia", "Stryber",
  ],
  Spain_Portugal: [
    "Glovo", "Cabify", "Factorial|factorial,factorialhr", "TravelPerk|travelperk,perk", "Typeform", "Wallapop", "Jobandtalent",
    "Holded", "Red Points|redpoints", "Kave Home|kavehome", "Seedtag", "Clarity AI|clarityai", "Fever", "Paack", "Devo",
    "Ontruck", "Badi", "Playtomic", "Sequra", "Payflow", "Codurance", "Unbabel", "Feedzai", "Talkdesk", "OutSystems",
    "Sword Health|swordhealth", "Remote|remote,remotecom", "Barkyn", "Jscrambler", "Coverflex", "Tonic App|tonicapp",
    "Probely", "Utrust", "Defined.ai|definedai", "Landing.jobs|landingjobs", "Indie Campers|indiecampers", "Anchorage",
    "Kitch", "Cleverbit", "Buzzvil", "Lodgify", "Holaluz", "Fintonic", "Bnext", "Rebellion Pay|rebellionpay", "Kantox",
    "Pagantis", "Housfy", "Idoven", "Mediktor", "Doctoralia", "Docplanner", "Cornerjob", "Userzoom", "Nuclio", "Nuclia",
    "Freepik", "Bitpanda", "Criptan", "Bit2Me|bit2me", "2Gether", "Luzia", "Multiverse Computing|multiversecomputing",
    "Quibim", "Tyris", "Ironhack", "Platzi", "Crehana", "Voicemod", "Kymatio", "Genially", "Emergya", "Paynopain", "Hivency",
    "Taxdown", "Colvin", "Gelt", "Stuart", "Deporvillage", "Privalia", "Letgo", "Minubo", "Onna", "Bipi", "Carto",
    "Bdeo", "Bcombinator", "Fanvue", "Anyone", "Mygon", "Uniplaces", "Doist", "Hole19", "Xpand IT", "Aptoide",
    "Farfetch", "Vizzia", "Knok", "Nomad Work|nomadwork", "Heptasense", "Automaise", "Swonkie", "Kuantokusta",
  ],
  Italy: [
    "Satispay", "Scalapay", "Casavo", "Prima", "Everli", "Moneyfarm", "Cortilia", "Bending Spoons|bendingspoons", "Musixmatch",
    "Soldo", "Treedom", "Wopta", "Contents", "Yolo", "Qomodo", "Hype", "Conio", "Young Platform|youngplatform",
    "Credimi", "Borsa del Credito", "Fabrick", "Moneyfarm", "Casavo", "Milkman", "Supermercato24", "Foorban", "Deliveristo",
    "Tannico", "Velasca", "Vivino", "Faire", "Jakala", "Aboca", "D-Orbit|dorbit", "Newcleo", "Kyber", "Datapizza",
    "Translated", "Indigo.ai|indigoai", "Aindo", "Axyon", "Wyscout", "Hiveon", "Weroad", "Freeda", "Il Post", "Bitmama",
  ],
  Belgium_Luxembourg: [
    "Collibra", "Showpad", "Odoo", "Teamleader", "Deliverect", "Lighthouse|lighthouse,mylighthouse", "Aikido|aikido,aikidosecurity",
    "Silverfin", "Awingu", "Lalaland", "Robovision", "Accountable", "Keyrock", "Bitstamp", "Lydia", "Trustbuilder", "Piano",
    "Payconiq", "Qover", "Belfius", "Luminus", "Unifiedpost", "Sortlist", "Timechimp", "Twikey", "Ponto", "Isabel",
    "Sentiance", "Aptus", "Nobi", "Hovr", "Poppy", "Cowboy", "Tekst", "Faros", "Mendix", "Aprimo", "Vanmoof", "Stoomlink",
    "Deliverect", "Tiller", "Aikido", "Cobbler", "Proxyclick", "Engagor", "Datacamp", "Swan", "Bizzy", "Salonkee",
    "Kneip", "Olkypay", "Lemonway", "Rakuten", "Talkwalker", "Kaiko", "Arendt", "Tadaweb", "Anybus", "Spire",
  ],
  Poland_CEE_Balkans: [
    "Docplanner", "Booksy", "Brainly", "Text|text,livechat", "Packhelp", "Infermedica", "UiPath|uipath", "Tidio", "Nomagic",
    "Synerise", "Ramp Network|ramp,rampnetwork", "Zen.com|zen,zencom", "Alokai|alokai,vuestorefront", "Productboard", "Mews",
    "Rohlik", "Apify", "Make|make,integromat", "Kiwi.com|kiwicom,kiwi", "FintechOS|fintechos", "Druid AI|druidai", "Payhawk",
    "Dronamics", "Quantive|quantive,gtmhub", "Infobip", "Rimac", "Nanobit", "Photomath", "Memgraph", "Microblink", "Gideon",
    "Viva Wallet|vivawallet", "Blueground", "Workable", "Skroutz", "Plum", "Exness", "Pipedrive", "Deel", "Toptal",
    "Bitdefender", "Elrond|multiversx", "Tremend", "Superbet", "Smartbill", "Frisbo", "Glovo", "Fintech Galaxy", "Instant",
    "Countr", "Tipalti", "Zonky", "Twisto", "Mall Group", "Pure Storage", "Rossum", "Socialbakers|emplifi", "Emplifi",
    "Behavio", "Avast", "Gen", "Cognito", "Ataccama", "Resistant AI|resistantai", "Blindspot", "Keboola", "Spaceti",
    "Sotio", "Kiwi", "Liftago", "Dámejídlo", "Foodora", "Brite", "Zonky", "Growjo", "Tidio", "Nethone", "Omnicalculator",
    "Livespace", "Sunscrapers", "Vue Storefront", "Autenti", "Kontomatik", "Tpay", "PayU", "Allegro", "InPost", "Eobuwie",
    "ElevenLabs", "Cosmose", "SentiOne", "Growbots", "Zowie", "Survicate", "Brand24", "Landingi", "Nozbe", "Surfer",
    "Hotjar", "Gamesys", "Superside", "Codility", "Tooploox", "STX Next", "Netguru", "10Clouds", "Vention", "Instamart",
  ],
  Global_Remote_First: [
    "Toggl", "Doist", "Hotjar", "Proton", "Automattic", "Remote|remotecom,remote", "Deel", "Oyster|oyster,oysterhr", "Zapier",
    "GitLab|gitlab", "Buffer", "Help Scout|helpscout", "Kraken|kraken,kraken.com,krakendigitalassetexchange", "Chainlink Labs|chainlinklabs",
    "Consensys", "Status|status,statusim", "Aragon", "Nethermind", "Ledger", "Parity", "Web3 Foundation", "Gnosis", "Safe",
    "Near Foundation", "MoonPay|moonpay", "Nansen", "Wintermute", "Keyrock", "Flowdesk", "Kiln", "Zama", "Kaiko",
    "Blockdaemon", "Figment", "Chorus One|chorusone", "P2P.org|p2porg", "Everstake", "Bitfury", "Hiro", "Aztec", "Starknet Foundation",
    "Mina Foundation", "Celestia", "Eigen Labs|eigenlabs", "Lido|lido,lidofinance", "Uniswap Labs|uniswaplabs", "OpenSea",
    "Dune", "Messari", "Coinshares", "Bitpanda", "Ramp", "Rarible", "Immutable", "Animoca", "Yield Guild", "Sky Mavis|skymavis",
    "Canonical", "Mattermost", "Sourcegraph", "Posthog|posthog", "Supabase", "Airbyte", "Grafana Labs|grafanalabs", "Tailscale",
    "Vercel", "Hashicorp", "Elastic", "Discourse", "Ghost", "Wikimedia", "Mozilla", "Brave", "DuckDuckGo", "Kinsta",
    "Human Made|humanmade", "10up", "Clevertech", "Toptal", "Turing", "Andela", "A.Team|ateam", "Hopper", "Hubstaff", "Time Doctor|timedoctor",
    "Scrapinghub|zyte", "Zyte", "Invisible", "Scale", "Surge", "Hims", "Lemon.io|lemonio", "Arc", "Jobbio", "Remotebase",
    "Workana", "Sticker Mule|stickermule", "Close|close,closeio", "Customer.io|customerio", "Loom", "Hypothesis", "Articulate",
    "Appwrite", "Strapi", "Directus", "Cal.com|calcom", "Plane", "Hoppscotch", "Infisical", "Novu", "Dagger", "Temporal",
  ],
  Australia: [
    "Canva", "Airwallex", "SafetyCulture", "Culture Amp|cultureamp", "Employment Hero|employmenthero", "Deputy", "Linktree",
    "Go1", "Rokt", "Immutable", "Eucalyptus", "Airtasker", "Zip|zip,zipco", "Tyro", "me&u|meandu,mryum", "Pet Circle|petcircle",
    "Heidi Health|heidihealth,heidi", "Leonardo.Ai|leonardoai", "Harrison.ai|harrisonai", "Relevance AI|relevanceai", "Lorikeet",
    "Buildkite", "SiteMinder|siteminder", "Brighte", "Workforce.com|workforcecom,tanda", "Mable", "Prospa", "Judo Bank|judobank",
    "Stake", "Pearler", "Spriggy", "Hipages", "Octopus Deploy|octopusdeploy", "LegalVision|legalvision", "Assignar",
    "Propeller Aero|propelleraero", "Q-CTRL|qctrl", "Silicon Quantum Computing", "Gilmour Space|gilmourspace", "Fleet Space|fleetspace",
    "Morse Micro|morsemicro", "Dovetail", "Coreplus", "Kasada", "Secure Code Warrior|securecodewarrior", "Simpro", "Sendle", "Shippit",
    "Zeller", "Cape", "Weel", "Till Payments|tillpayments", "Lendi", "Athena|athena,athenahomeloans", "Nitro", "Instaclustr",
    "Mad Paws|madpaws", "Finch", "Carted", "Vervoe", "Pyn", "Loop", "Midas", "Waddle", "Flare", "Rezdy", "Tidal", "Easy Agile|easyagile",
    "Hnry", "Sharesies", "Superhero", "Spaceship", "Raiz", "Brighter Super", "CommBank", "Up", "Volt", "86 400|86400",
    "Tic:Toc|tictoc", "Credi", "Wisr", "Plenti", "MoneyMe", "Splend", "Uber Carshare", "Evie Networks|evienetworks", "Jet Charge|jetcharge",
    "Amber Electric|amberelectric", "Sun Cable|suncable", "Hysata", "Allume", "5B", "SunDrive", "Infinite Aerospace",
    "Cognitiv", "Marketplacer", "Eftsure", "Airtree", "Blackbird", "Square Peg|squarepeg", "Mutinex", "Particular Audience|particularaudience",
    "Growth Faculty", "Compono", "Crowd Media", "Blinq", "Mr Yum", "Ordermentum", "Limepay", "Payright", "Deel", "Zoox",
    "Lyrebird Health|lyrebirdhealth", "Eucalyptus", "Vow", "Cauldron", "Loam Bio|loambio", "All G|allg", "Nourish Ingredients",
    "Trace", "Neara", "Aurecon", "Checkbox", "Clipchamp", "Envato", "99designs", "Freelancer", "Campaign Monitor|campaignmonitor",
    "Prezzee", "Humanforce", "ELMO", "Enboarder", "Applied", "Rippl", "Crossmint", "Swyftx", "CoinJar|coinjar", "Independent Reserve|independentreserve",
    "BTC Markets|btcmarkets", "Blockchain Australia", "Rapid", "Zepto", "Monoova", "Cuscal", "Novatti", "Paypa Plane", "Basiq",
    "Frollo", "Adatree", "Proviso", "Anchor", "Arkade", "Unlockd",
  ],
  New_Zealand: [
    "Xero", "Hnry", "Tradify", "Sharesies", "Halter", "Rocket Lab|rocketlab", "Timely", "Crimson Education|crimsoneducation",
    "Pushpay", "Serko", "Education Perfect|educationperfect", "Cin7", "Tracksuit|tracksuit,gotracksuit", "Parkable", "Partly",
    "Kami", "Dawn Aerospace|dawnaerospace", "Mint Innovation|mintinnovation", "Soul Machines|soulmachines", "Figured",
    "Unleashed Software|unleashed,unleashedsoftware", "AskNicely|asknicely", "Raygun", "PaySauce", "Joyous", "Portainer",
    "Vend", "Blinc", "Laybuy", "Qrious", "Mobi2Go", "Plink", "Wipster", "Sitehost", "Pax8", "Octopus", "Kami", "Lightspeed",
    "Hatch", "Kernel", "Fonterra", "Mimica", "Lumin", "Ezybook", "Nyriad", "Loyalty NZ", "Cloudfinch", "Zeal", "Pandapay",
    "Tradie", "Carbn", "Parrot Analytics|parrotanalytics", "Toku", "Fabric", "Ribbon", "Gorilla Technology", "LawVu|lawvu",
    "Aeroqual", "Aroa", "Orbica", "BlackSky", "Te Rua", "Rush Digital", "Sweat Equity", "Dexibit", "Montoux", "Kōkako",
    "ZeroFriction", "Pikselin", "Bolt Rocket", "Emrex", "Lynx", "Ackama", "Datacom", "Payroller", "iPayroll", "Smartpay",
    "Paymark", "Swiftpay", "Mighty Ape", "The Warehouse", "Foodstuffs", "Chnnl", "Cogo|cogo", "Kara", "Ferve", "Clearpay",
  ],
};

// Large corporates / non-target / India-HQ names that slipped in — skipped during discovery.
export const BLOCK = new Set([
  "Hubspot", "Salesforce", "Paypal", "Zalando", "Booking", "Adyen", "Delivery Hero", "Hellofresh", "Stripe", "Zendesk",
  "Unity", "Vestas", "Ørsted", "Kongsberg", "Swarovski", "Swiss Post", "Belfius", "Rakuten", "Allegro", "Fonterra",
  "The Warehouse", "Foodstuffs", "CommBank", "Tiktok", "Travelport", "Squarespace", "Toast", "Dynatrace", "Ubisoft",
  "Visma", "Lloyds", "Coinbase", "Mercury", "Gemini", "Lemonade", "Hinge", "Bumble", "Airfryer", "Growjo", "Instamart",
  "Remotebase", "Zoox", "Aurecon", "Datacom", "Hims", "Wikimedia", "Takeaway", "Coolblue", "Bol", "Rituals",
  "Hunkemöller", "Kuehne", "Stepstone", "Farfetch", "Privalia", "Letgo", "Elastic", "Sinch", "Polestar", "Nobina",
  "Glimstedt", "Luminar", "Nordnet", "Svea", "Crayon", "Tietoevry", "Mehiläinen", "Kapsch", "Frequentis", "Payone",
  "Klim", "Sophia Genetics", "Pure Storage", "Avast", "Gen", "PayU", "InPost", "Gamesys", "Waterford", "Leadership",
  "Integrate", "Ding", "Viatel", "Openet", "Cloud Nine", "Enable", "Surfsara", "Knab", "Invest-NL", "Sympany", "Kramp",
  "Il Post", "Aboca", "Jakala", "Faire", "Luminus", "Isabel", "Piano", "Rapid", "Anchor", "Applied", "Trace", "Loop",
  "Ghost", "Arc", "Surge", "Scale", "Invisible", "Hatch", "Kernel", "Fabric", "Ribbon", "Octopus", "Cape", "Finch", "Ava",
  "On", "Up", "Volt", "Side", "Hive", "Karma", "Emma", "Dexter", "Peaks", "Contents", "Heroes", "Adapt", "Genie", "Unique",
  "Shape", "Tame", "Evida", "Change", "Ada", "Fjord", "Bid", "Kron", "Payr", "Neon", "Descartes", "Largo", "Verity", "Spire",
  "Vow", "Cauldron", "Midas", "Waddle", "Flare", "Tidal", "Pyn", "Credi", "Zeal", "Kara", "Ferve", "Lynx", "Toku", "Plink",
  "Lumin", "Mimica", "Instant", "Frontier", "Emrex", "Hugo", "Opti", "Mnd", "Ctrl", "Tessin", "Wint", "Majority", "Hemma",
  "Gorilla Technology", "BlackSky", "Te Rua", "Bolt Rocket", "Smartpay", "Paymark", "Swiftpay", "Mighty Ape", "Chnnl",
  "Clearpay", "Swoop", "Stoomlink", "Nobi", "Hovr", "Poppy", "Tekst", "Faros", "Aprimo", "Spire", "Aptus", "Heartcore",
  "Hygge", "ChargePoint", "Voluntarily", "Everfund", "Hiper", "Zolar", "Cobra", "Beams", "Formo", "Mall Group", "Gideon",
  "Dámejídlo", "Foodora", "Cognito", "Tremend", "Fintech Galaxy", "Countr", "Anyone", "Bcombinator", "Knok", "Heptasense",
  "Minubo", "Onna", "Bipi", "Colvin", "Gelt", "Luzia", "Tyris", "Kymatio", "Emergya", "Hivency", "Vizzia", "Mygon",
  "Growth Faculty", "Compono", "Crowd Media", "Blockchain Australia", "Novatti", "Cuscal", "Proviso", "Arkade", "Unlockd",
  "Nuclear Power", "Hy24", "Nel", "Zelo", "Bluefish", "Ignite", "Dignio", "Scoutbase", "Trainerly", "Neodroid", "Kiwi",
]);
